<?php
require_once __DIR__.'/../../core/db_connect.php';require_once __DIR__.'/../../core/bible_studies.php';bs_require_eligible($pdo);
header('Cache-Control: private, no-store');
if(bs_role()!=='super_admin'){http_response_code(403);exit('Super administrator access required.');}
if(!bs_schema_ready($pdo)){
    $missingBibleStudyTables=bs_missing_tables($pdo);
    http_response_code(503);$page_title='Bible Study Administration';ob_start();
    ?><div class="alert alert-warning" role="alert"><h1 class="h4">Bible Study database setup is incomplete</h1><p>Install the following missing tables before using this page:</p><ul class="mb-0"><?php foreach($missingBibleStudyTables as $missingTable):?><li><code><?=escape($missingTable)?></code></li><?php endforeach;?></ul></div><?php
    $content=ob_get_clean();include __DIR__.'/../portal/layout.php';exit;
}
$parseRegistrationDate = static function (string $date, string $label, bool $endOfDay = false): string {
    $value = trim($date);
    $parsed = DateTimeImmutable::createFromFormat('!Y-m-d', $value, new DateTimeZone(BS_TIMEZONE));
    $errors = DateTimeImmutable::getLastErrors();
    if (!$parsed || ($errors !== false && ($errors['warning_count'] > 0 || $errors['error_count'] > 0)) || $parsed->format('Y-m-d') !== $value) {
        throw new InvalidArgumentException("Enter a valid {$label} date.");
    }
    if ($endOfDay) $parsed = $parsed->setTime(23, 59, 59);
    return $parsed->format('Y-m-d H:i:s');
};
$message='';$error='';
try{if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){bs_require_post();$action=$_POST['action']??'';
 if($action==='create'){
  $date=(string)($_POST['study_date']??'');$d=DateTimeImmutable::createFromFormat('!Y-m-d',$date,new DateTimeZone(BS_TIMEZONE));if(!$d||$d->format('Y-m-d')!==$date||$d->format('N')!=='1')throw new InvalidArgumentException('Select a valid Monday.');
  $title=trim((string)($_POST['title']??''));if($title===''||mb_strlen($title)>180)throw new InvalidArgumentException('Enter a valid title.');
  $opens=$parseRegistrationDate((string)($_POST['registration_opens_date']??''),'registration opening');
  $deadline=$parseRegistrationDate((string)($_POST['registration_deadline_date']??''),'registration deadline',true);
  if(new DateTimeImmutable($opens,new DateTimeZone(BS_TIMEZONE))>=new DateTimeImmutable($deadline,new DateTimeZone(BS_TIMEZONE)))throw new InvalidArgumentException('The registration deadline must be after registration opens.');
  $selectedSessions=$_POST['sessions']??[];$allowedSessions=['morning','midday','evening'];
  if(!is_array($selectedSessions)||$selectedSessions===[]||array_diff($selectedSessions,$allowedSessions))throw new InvalidArgumentException('Select at least one valid Bible Study session.');
  $selectedSessions=array_values(array_unique($selectedSessions));
  $leader=bs_positive_int($_POST['leader_user_id']??null,'leader');if(!bs_eligible_user($pdo,$leader))throw new InvalidArgumentException('Leader is not eligible.');
  $pdo->beginTransaction();$q=$pdo->prepare('INSERT INTO bible_studies(study_date,title,primary_scripture,preparation_instructions,registration_opens_at,registration_deadline,created_by) VALUES(?,?,?,?,?,?,?)');$q->execute([$date,$title,trim($_POST['primary_scripture']??''),trim($_POST['preparation_instructions']??''),$opens,$deadline,bs_user_id()]);$id=(int)$pdo->lastInsertId();
  $sessionInsert=$pdo->prepare('INSERT INTO bible_study_sessions(bible_study_id,session_name,start_time,end_time,is_active,display_order) VALUES(?,?,?,?,?,?)');$sessionInsert->execute([$id,'Morning Session','08:00:00','10:00:00',in_array('morning',$selectedSessions,true)?1:0,1]);$sessionInsert->execute([$id,'Midday Session','11:00:00','13:00:00',in_array('midday',$selectedSessions,true)?1:0,2]);$sessionInsert->execute([$id,'Evening Session','18:30:00','20:00:00',in_array('evening',$selectedSessions,true)?1:0,3]);$pdo->prepare('INSERT INTO bible_study_leader_assignments(bible_study_id,leader_user_id,appointed_by) VALUES(?,?,?)')->execute([$id,$leader,bs_user_id()]);bs_audit($pdo,'study_created','study',$id,['active_sessions'=>$selectedSessions]);bs_audit($pdo,'leader_appointed','study',$id,['leader_user_id'=>$leader]);$pdo->commit();$message='Study created with the selected sessions.';
 }else{$id=bs_positive_int($_POST['study_id']??null,'study');
  if($action==='status'){$status=(string)($_POST['status']??'');if(!in_array($status,['published','completed','cancelled','archived'],true))throw new InvalidArgumentException('Invalid status.');$reason=trim((string)($_POST['reason']??''));if($status==='cancelled'&&$reason==='')throw new InvalidArgumentException('Cancellation reason is required.');$published=$status==='published'?',published_at=COALESCE(published_at,NOW())':'';$completed=$status==='completed'?',completed_at=NOW()':'';$q=$pdo->prepare("UPDATE bible_studies SET status=?,cancellation_reason=? {$published}{$completed} WHERE id=?");$q->execute([$status,$reason?:null,$id]);bs_audit($pdo,'study_'.$status,'study',$id,['reason'=>$reason]);$message='Study status updated.';}
  elseif($action==='replace_leader'){$leader=bs_positive_int($_POST['leader_user_id']??null,'leader');$reason=trim((string)($_POST['reason']??''));if($reason===''||!bs_eligible_user($pdo,$leader))throw new InvalidArgumentException('Eligible leader and replacement reason are required.');$pdo->beginTransaction();$pdo->prepare('UPDATE bible_study_leader_assignments SET is_current=0,ended_at=NOW(),replacement_reason=? WHERE bible_study_id=? AND is_current=1')->execute([$reason,$id]);$pdo->prepare('INSERT INTO bible_study_leader_assignments(bible_study_id,leader_user_id,appointed_by) VALUES(?,?,?)')->execute([$id,$leader,bs_user_id()]);bs_audit($pdo,'leader_replaced','study',$id,['leader_user_id'=>$leader,'reason'=>$reason]);$pdo->commit();$message='Leader replaced; history was preserved.';}
  else throw new InvalidArgumentException('Invalid action.');
 }}
}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();error_log('[bible_study_admin] '.$e->getMessage());$error=$e instanceof PDOException?'The operation could not be completed.':$e->getMessage();}
$leaders=$pdo->query("SELECT id,name,email FROM users WHERE role IN ('member','admin','super_admin') AND (category NOT IN ('partner','missionary') OR is_approved=1) ORDER BY name")->fetchAll();
$studies=$pdo->query("SELECT b.id,b.study_date,b.title,b.status,b.registration_deadline,u.name leader_name,(SELECT COUNT(*) FROM bible_study_registrations r WHERE r.bible_study_id=b.id AND r.status='active') registrations,(SELECT GROUP_CONCAT(s.session_name ORDER BY s.display_order SEPARATOR ', ') FROM bible_study_sessions s WHERE s.bible_study_id=b.id AND s.is_active=1) active_sessions FROM bible_studies b LEFT JOIN bible_study_leader_assignments la ON la.bible_study_id=b.id AND la.is_current=1 LEFT JOIN users u ON u.id=la.leader_user_id ORDER BY b.study_date DESC LIMIT 100")->fetchAll();
$page_title='Bible Study Administration';$page_styles=[BASE_PATH.'/assets/css/bible_study.css'];ob_start();
?><div class="d-flex flex-wrap justify-content-between align-items-center mb-4"><div><h1 class="h2">General Bible Study administration</h1><p class="text-muted mb-0">Create studies, appoint leaders and control publication.</p></div><a href="bible_study.php" class="btn btn-outline-primary">Member view</a></div><?php if($message):?><div class="alert alert-success"><?=escape($message)?></div><?php endif;if($error):?><div class="alert alert-danger"><?=escape($error)?></div><?php endif;?>
<div class="card mb-4"><div class="card-header"><h2 class="h5 mb-0">Create a Monday study</h2></div><div class="card-body"><form method="post" class="row g-3"><?=csrf_field()?><input type="hidden" name="action" value="create"><div class="col-md-4"><label class="form-label">Monday date</label><input class="form-control" type="date" name="study_date" required></div><div class="col-md-8"><label class="form-label">Title</label><input class="form-control" name="title" maxlength="180" required></div><div class="col-md-6"><label class="form-label">Primary scripture</label><input class="form-control" name="primary_scripture" maxlength="255"></div><div class="col-md-6"><label class="form-label">Leader</label><select class="form-select" name="leader_user_id" required><option value="">Select</option><?php foreach($leaders as $l):?><option value="<?=(int)$l['id']?>"><?=escape($l['name'].' — '.$l['email'])?></option><?php endforeach;?></select></div><div class="col-md-6"><label class="form-label" for="registration_opens_date">Registration opens</label><input class="form-control" id="registration_opens_date" type="date" name="registration_opens_date" required></div><div class="col-md-6"><label class="form-label" for="registration_deadline_date">Registration deadline</label><input class="form-control" id="registration_deadline_date" type="date" name="registration_deadline_date" required></div><fieldset class="col-12"><legend class="h6 mb-2">Available sessions</legend><p class="small text-muted mb-2">Choose the sessions members may register for. All three are selected by default.</p><div class="row g-2"><div class="col-md-4"><label class="border rounded p-3 d-flex gap-2 h-100"><input class="form-check-input" type="checkbox" name="sessions[]" value="morning" checked><span><strong class="d-block">Morning Session</strong><small class="text-muted">08:00–10:00</small></span></label></div><div class="col-md-4"><label class="border rounded p-3 d-flex gap-2 h-100"><input class="form-check-input" type="checkbox" name="sessions[]" value="midday" checked><span><strong class="d-block">Midday Session</strong><small class="text-muted">11:00–13:00</small></span></label></div><div class="col-md-4"><label class="border rounded p-3 d-flex gap-2 h-100"><input class="form-check-input" type="checkbox" name="sessions[]" value="evening" checked><span><strong class="d-block">Evening Session</strong><small class="text-muted">18:30–20:00</small></span></label></div></div></fieldset><div class="col-12"><label class="form-label">Preparation instructions</label><textarea class="form-control" name="preparation_instructions" rows="3"></textarea></div><div><button class="btn btn-primary">Create study</button></div></form></div></div>
<h2 class="h4">All studies</h2><?php if(!$studies):?><div class="alert alert-info">No studies created.</div><?php endif;?><div class="row g-3"><?php foreach($studies as $s):?><div class="col-12"><div class="card"><div class="card-body"><div class="d-flex flex-wrap justify-content-between gap-2"><div><h3 class="h5 mb-1"><?=escape($s['title'])?></h3><span><?=escape($s['study_date'])?> · <?=escape($s['leader_name']?:'No leader')?> · <?=(int)$s['registrations']?> registrations</span><div class="small mt-1"><strong>Sessions:</strong> <?=escape($s['active_sessions']?:'None active')?></div></div><span class="badge bg-secondary align-self-start"><?=escape($s['status'])?></span></div><div class="row g-2 mt-2"><div class="col-lg-6"><form method="post" class="d-flex flex-wrap gap-2"><?=csrf_field()?><input type="hidden" name="action" value="status"><input type="hidden" name="study_id" value="<?=(int)$s['id']?>"><select class="form-select form-select-sm w-auto" name="status"><option>published</option><option>completed</option><option>cancelled</option><option>archived</option></select><input class="form-control form-control-sm flex-grow-1" name="reason" placeholder="Reason (required for cancellation)"><button class="btn btn-sm btn-primary">Update</button></form></div><div class="col-lg-6"><form method="post" class="d-flex flex-wrap gap-2"><?=csrf_field()?><input type="hidden" name="action" value="replace_leader"><input type="hidden" name="study_id" value="<?=(int)$s['id']?>"><select class="form-select form-select-sm w-auto" name="leader_user_id" required><?php foreach($leaders as $l):?><option value="<?=(int)$l['id']?>"><?=escape($l['name'])?></option><?php endforeach;?></select><input class="form-control form-control-sm flex-grow-1" name="reason" placeholder="Replacement reason" required><button class="btn btn-sm btn-outline-primary">Replace leader</button></form></div></div><a class="btn btn-sm btn-link px-0 mt-2" href="bible_study_leader.php?study_id=<?=(int)$s['id']?>">Open management view</a></div></div></div><?php endforeach;?></div>
<?php $content=ob_get_clean();include __DIR__.'/../portal/layout.php';
