<?php
require_once __DIR__.'/../../core/db_connect.php'; require_once __DIR__.'/../../core/bible_studies.php';
header('Cache-Control: private, no-store');
$user=bs_require_eligible($pdo); $uid=(int)$user['id']; $message='';$error='';
if(!bs_schema_ready($pdo)){
    http_response_code(503);$page_title='General Bible Study';$page_styles=[BASE_PATH.'/assets/css/bible_study.css'];ob_start();
    ?><div class="bs-hero mb-4"><div><h1 class="h2 mb-1">General Bible Study</h1><p class="mb-0">Learn, reflect and grow together.</p></div></div><div class="alert alert-info" role="status"><h2 class="h5">Bible Study is being prepared</h2><p class="mb-0">This section is temporarily unavailable while setup is completed. Please try again shortly.</p></div><?php
    $content=ob_get_clean();include __DIR__.'/../portal/layout.php';exit;
}
try {
 if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
  bs_require_post();$action=$_POST['action']??'';$studyId=bs_positive_int($_POST['study_id']??null,'study');
  if($action==='register')bs_register($pdo,$studyId,bs_positive_int($_POST['session_id']??null,'session'),$uid);
  elseif($action==='cancel')bs_cancel_registration($pdo,$studyId,$uid);
  elseif($action==='save_note')bs_save_note($pdo,$studyId,$uid,trim((string)($_POST['note_content']??'')));
  else throw new InvalidArgumentException('Invalid action.');
  $message=$action==='save_note'?'Private note saved.':'Registration updated.';
 }
}catch(Throwable $e){error_log('[bible_study] '.$e->getMessage());$error=$e instanceof PDOException?'The request could not be completed.':$e->getMessage();}
$q=$pdo->query("SELECT b.id FROM bible_studies b WHERE b.status='published' AND b.study_date>=CURDATE() ORDER BY b.study_date LIMIT 1");$studyId=(int)$q->fetchColumn();$study=$studyId?bs_study($pdo,$studyId):null;
$sessions=$study?array_values(array_filter(bs_sessions($pdo,$studyId),static fn(array $session):bool=>(int)$session['is_active']===1)):[];$registration=$study?bs_active_registration($pdo,$studyId,$uid):null;$window=$study?bs_registration_window($study):null;
$materials=[];$note='';if($study){$q=$pdo->prepare('SELECT id,material_title,description,original_filename,file_size FROM bible_study_materials WHERE bible_study_id=? AND is_published=1 ORDER BY created_at');$q->execute([$studyId]);$materials=$q->fetchAll();$q=$pdo->prepare('SELECT note_content FROM bible_study_notes WHERE bible_study_id=? AND member_user_id=?');$q->execute([$studyId,$uid]);$note=(string)($q->fetchColumn()?:'');}
$q=$pdo->prepare("SELECT b.study_date,b.title,b.status,r.status registration_status,s.session_name,a.attendance_status FROM bible_study_registrations r JOIN bible_studies b ON b.id=r.bible_study_id JOIN bible_study_sessions s ON s.id=r.session_id LEFT JOIN bible_study_attendance a ON a.registration_id=r.id WHERE r.member_user_id=? AND (b.study_date<CURDATE() OR b.status IN ('completed','cancelled','archived')) ORDER BY b.study_date DESC LIMIT 25");$q->execute([$uid]);$history=$q->fetchAll();
$page_title='General Bible Study';$page_styles=[BASE_PATH.'/assets/css/bible_study.css'];ob_start();
?>
<div class="bs-hero mb-4"><div><span class="badge bg-light text-primary mb-2">Every Monday</span><h1 class="h2 mb-1">General Bible Study</h1><p class="mb-0">Learn, reflect and grow together.</p></div></div>
<?php if($message):?><div class="alert alert-success" role="status"><?=escape($message)?></div><?php endif;if($error):?><div class="alert alert-danger" role="alert"><?=escape($error)?></div><?php endif;?>
<?php if(!$study):?><div class="card"><div class="card-body text-center py-5"><i class="bi bi-calendar2-heart display-5 text-muted"></i><h2 class="h5 mt-3">No upcoming study is published</h2><p class="text-muted mb-0">Please check back soon.</p></div></div><?php else:?>
<section class="card shadow-sm mb-4"><div class="card-body p-3 p-md-4"><div class="d-flex flex-wrap justify-content-between gap-2"><div><span class="badge bg-success"><?=escape(ucfirst($study['status']))?></span><h2 class="h3 mt-2 mb-1"><?=escape($study['title'])?></h2></div><div class="text-md-end"><strong><?=escape(date('l, j F Y',strtotime($study['study_date'])))?></strong><div class="text-muted">Leader: <?=escape($study['leader_name']?:'To be announced')?></div></div></div><hr><dl class="row mb-0"><dt class="col-sm-3">Scripture</dt><dd class="col-sm-9"><?=escape($study['primary_scripture'])?><?php if($study['additional_scriptures']):?><br><small><?=nl2br(escape($study['additional_scriptures']))?></small><?php endif;?></dd><dt class="col-sm-3">Prepare</dt><dd class="col-sm-9"><?=nl2br(escape($study['preparation_instructions']))?></dd><dt class="col-sm-3">Deadline</dt><dd class="col-sm-9"><?=escape(date('j M Y, H:i',strtotime($study['registration_deadline'])))?> EAT</dd></dl></div></section>
<?php if($window):?><div class="alert alert-info"><?=escape($window)?></div><?php endif;?>
<div class="row g-3 mb-4"><?php foreach($sessions as $s):$full=$s['capacity']!==null&&(int)$s['registered_count']>=(int)$s['capacity'];$selected=$registration&&(int)$registration['session_id']===(int)$s['id'];?><div class="col-12 col-md-4"><article class="card h-100 session-card <?=$selected?'selected':''?>"><div class="card-body"><div class="d-flex justify-content-between"><h3 class="h5"><?=escape($s['session_name'])?></h3><?php if($selected):?><span class="badge bg-primary">Selected</span><?php endif;?></div><p class="mb-2"><i class="bi bi-clock"></i> <?=escape(substr($s['start_time'],0,5))?>–<?=escape(substr($s['end_time'],0,5))?></p><p class="small text-muted"><?=$s['capacity']===null?'Unlimited capacity':escape((string)max(0,(int)$s['capacity']-(int)$s['registered_count'])).' places remaining'?></p><?php if(!$window&&!$full&&!$selected):?><form method="post"><?=csrf_field()?><input type="hidden" name="action" value="register"><input type="hidden" name="study_id" value="<?=$studyId?>"><input type="hidden" name="session_id" value="<?=(int)$s['id']?>"><button class="btn btn-primary w-100"><?=$registration?'Change to this session':'Select session'?></button></form><?php elseif($full&&!$selected):?><button class="btn btn-secondary w-100" disabled>Full</button><?php endif;?></div></article></div><?php endforeach;?></div>
<?php if($registration&&!$window):?><form method="post" class="mb-4"><?=csrf_field()?><input type="hidden" name="action" value="cancel"><input type="hidden" name="study_id" value="<?=$studyId?>"><button class="btn btn-outline-danger" onclick="return confirm('Cancel your registration?')">Cancel registration</button></form><?php endif;?>
<div class="row g-4"><div class="col-lg-6"><section class="card h-100"><div class="card-body"><h2 class="h5">Study materials</h2><?php if(!$materials):?><p class="text-muted">No materials have been published.</p><?php else:?><ul class="list-group list-group-flush"><?php foreach($materials as $m):?><li class="list-group-item px-0"><a href="bible_study_download.php?material_id=<?=(int)$m['id']?>"><?=escape($m['material_title'])?></a><small class="d-block text-muted"><?=escape($m['original_filename'])?></small></li><?php endforeach;?></ul><?php endif;?></div></section></div><div class="col-lg-6"><section class="card h-100"><div class="card-body"><h2 class="h5">My private notes</h2><p class="small text-muted">Only you can view these notes.</p><form method="post"><?=csrf_field()?><input type="hidden" name="action" value="save_note"><input type="hidden" name="study_id" value="<?=$studyId?>"><label class="visually-hidden" for="note_content">Private notes</label><textarea class="form-control mb-2" id="note_content" name="note_content" maxlength="10000" rows="6"><?=escape($note)?></textarea><button class="btn btn-primary">Save notes</button></form></div></section></div></div>
<?php endif;?>
<section class="mt-4"><h2 class="h4">Previous studies and attendance</h2><?php if(!$history):?><p class="text-muted">No study history yet.</p><?php else:?><div class="list-group"><?php foreach($history as $h):?><div class="list-group-item d-flex flex-wrap justify-content-between"><span><strong><?=escape($h['title'])?></strong> · <?=escape($h['session_name'])?></span><span><?=escape($h['study_date'])?> · <?=escape($h['attendance_status']?:'not recorded')?></span></div><?php endforeach;?></div><?php endif;?></section>
<?php $content=ob_get_clean();include __DIR__.'/../portal/layout.php';
