<?php
require_once __DIR__.'/../../core/db_connect.php';require_once __DIR__.'/../../core/bible_studies.php';bs_require_eligible($pdo);
header('Cache-Control: private, no-store');
if(!bs_schema_ready($pdo)){
    http_response_code(503);$page_title='Bible Study Leader';ob_start();
    ?><div class="alert alert-info" role="status"><h1 class="h4">Bible Study is being prepared</h1><p class="mb-0">The database setup is not complete yet. Please try again shortly.</p></div><?php
    $content=ob_get_clean();include __DIR__.'/../portal/layout.php';exit;
}
$studyId=isset($_GET['study_id'])?bs_positive_int($_GET['study_id'],'study'):0;
if(!$studyId){$q=$pdo->prepare('SELECT bible_study_id FROM bible_study_leader_assignments WHERE leader_user_id=? ORDER BY is_current DESC,appointed_at DESC LIMIT 1');$q->execute([bs_user_id()]);$studyId=(int)$q->fetchColumn();}
if(!$studyId||!bs_can_manage($pdo,$studyId)){http_response_code(403);exit('You are not assigned to this study.');}
$message='';$error='';
try{if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){bs_require_post();$posted=bs_positive_int($_POST['study_id']??null,'study');if($posted!==$studyId||!bs_can_manage($pdo,$posted))throw new RuntimeException('Not authorized.');$action=$_POST['action']??'';
 if($action==='edit'){$title=trim((string)($_POST['title']??''));if($title===''||mb_strlen($title)>180)throw new InvalidArgumentException('Title is required.');$q=$pdo->prepare('UPDATE bible_studies SET title=?,primary_scripture=?,additional_scriptures=?,preparation_instructions=?,shared_summary=?,meeting_link=? WHERE id=?');$q->execute([$title,trim($_POST['primary_scripture']??''),trim($_POST['additional_scriptures']??''),trim($_POST['preparation_instructions']??''),trim($_POST['shared_summary']??''),filter_var(trim($_POST['meeting_link']??''),FILTER_VALIDATE_URL)?:null,$studyId]);bs_audit($pdo,'study_content_updated','study',$studyId);$message='Study details saved.';}
 elseif($action==='upload'){bs_upload_material($pdo,$studyId,$_FILES['material']??[],trim((string)($_POST['material_title']??'')),!empty($_POST['is_published']));$message='Material uploaded securely.';}
 elseif($action==='attendance'){$rid=bs_positive_int($_POST['registration_id']??null,'registration');$status=(string)($_POST['attendance_status']??'');if(!in_array($status,['not_recorded','present','absent','excused'],true))throw new InvalidArgumentException('Invalid attendance status.');$q=$pdo->prepare("SELECT 1 FROM bible_study_registrations WHERE id=? AND bible_study_id=? AND status='active'");$q->execute([$rid,$studyId]);if(!$q->fetchColumn())throw new RuntimeException('Registration not found.');$q=$pdo->prepare('INSERT INTO bible_study_attendance(registration_id,attendance_status,recorded_by,recorded_at) VALUES(?,?,?,NOW()) ON DUPLICATE KEY UPDATE attendance_status=VALUES(attendance_status),recorded_by=VALUES(recorded_by),recorded_at=NOW()');$q->execute([$rid,$status,bs_user_id()]);bs_audit($pdo,'attendance_changed','registration',$rid,['status'=>$status]);$message='Attendance updated.';}
 else throw new InvalidArgumentException('Invalid action.');
}}catch(Throwable $e){error_log('[bible_study_leader] '.$e->getMessage());$error=$e instanceof PDOException?'The operation could not be completed.':$e->getMessage();}
$study=bs_study($pdo,$studyId);$sessions=bs_sessions($pdo,$studyId);$q=$pdo->prepare("SELECT r.id,r.session_id,u.name,u.email,a.attendance_status FROM bible_study_registrations r JOIN users u ON u.id=r.member_user_id LEFT JOIN bible_study_attendance a ON a.registration_id=r.id WHERE r.bible_study_id=? AND r.status='active' ORDER BY r.session_id,u.name");$q->execute([$studyId]);$participants=$q->fetchAll();$q=$pdo->prepare('SELECT id,material_title,original_filename,is_published,created_at FROM bible_study_materials WHERE bible_study_id=? ORDER BY created_at DESC');$q->execute([$studyId]);$materials=$q->fetchAll();
$page_title='Bible Study Leader';$page_styles=[BASE_PATH.'/assets/css/bible_study.css'];ob_start();
?><div class="d-flex flex-wrap justify-content-between mb-4"><div><h1 class="h2">Study leader workspace</h1><p class="text-muted"><?=escape($study['study_date'])?> · <?=escape($study['status'])?></p></div><a class="btn btn-outline-primary align-self-start" href="bible_study.php">Member view</a></div><?php if($message):?><div class="alert alert-success"><?=escape($message)?></div><?php endif;if($error):?><div class="alert alert-danger"><?=escape($error)?></div><?php endif;?>
<div class="card mb-4"><div class="card-header"><h2 class="h5 mb-0">Study content</h2></div><div class="card-body"><form method="post" class="row g-3"><?=csrf_field()?><input type="hidden" name="action" value="edit"><input type="hidden" name="study_id" value="<?=$studyId?>"><div class="col-md-6"><label class="form-label">Title</label><input class="form-control" name="title" maxlength="180" required value="<?=escape($study['title'])?>"></div><div class="col-md-6"><label class="form-label">Primary scripture</label><input class="form-control" name="primary_scripture" maxlength="255" value="<?=escape($study['primary_scripture'])?>"></div><div class="col-md-6"><label class="form-label">Additional scriptures</label><textarea class="form-control" name="additional_scriptures"><?=escape($study['additional_scriptures'])?></textarea></div><div class="col-md-6"><label class="form-label">Preparation instructions</label><textarea class="form-control" name="preparation_instructions" rows="4"><?=escape($study['preparation_instructions'])?></textarea></div><div class="col-md-6"><label class="form-label">Meeting link</label><input class="form-control" type="url" name="meeting_link" maxlength="500" value="<?=escape($study['meeting_link'])?>"></div><div class="col-12"><label class="form-label">Published shared summary</label><textarea class="form-control" name="shared_summary" rows="5"><?=escape($study['shared_summary'])?></textarea></div><div><button class="btn btn-primary">Save details</button></div></form></div></div>
<div class="card mb-4"><div class="card-header"><h2 class="h5 mb-0">Materials</h2></div><div class="card-body"><form method="post" enctype="multipart/form-data" class="row g-2 align-items-end"><?=csrf_field()?><input type="hidden" name="action" value="upload"><input type="hidden" name="study_id" value="<?=$studyId?>"><div class="col-md-4"><label class="form-label">Title</label><input class="form-control" name="material_title" maxlength="180" required></div><div class="col-md-5"><label class="form-label">PDF, DOCX, PPTX, JPEG, PNG or WebP (10 MB)</label><input class="form-control" type="file" name="material" required accept=".pdf,.docx,.pptx,.jpg,.jpeg,.png,.webp"></div><div class="col-md-3"><div class="form-check mb-2"><input class="form-check-input" type="checkbox" name="is_published" id="published"><label class="form-check-label" for="published">Publish now</label></div><button class="btn btn-primary">Upload</button></div></form><?php foreach($materials as $m):?><div class="border-top mt-3 pt-2"><?=escape($m['material_title'])?> <span class="badge bg-<?=$m['is_published']?'success':'secondary'?>"><?=$m['is_published']?'Published':'Private'?></span></div><?php endforeach;?></div></div>
<h2 class="h4">Registrations and attendance</h2><div class="row g-3"><?php foreach($sessions as $s):?><div class="col-12 col-xl-4"><section class="card h-100"><div class="card-header"><strong><?=escape($s['session_name'])?></strong><span class="badge bg-primary float-end"><?=(int)$s['registered_count']?></span></div><div class="card-body p-2"><?php $found=false;foreach($participants as $p):if((int)$p['session_id']!==(int)$s['id']){continue;}$found=true;?><div class="border-bottom py-2"><strong><?=escape($p['name'])?></strong><small class="d-block text-muted"><?=escape($p['email'])?></small><form method="post" class="d-flex gap-2 mt-1"><?=csrf_field()?><input type="hidden" name="action" value="attendance"><input type="hidden" name="study_id" value="<?=$studyId?>"><input type="hidden" name="registration_id" value="<?=(int)$p['id']?>"><select class="form-select form-select-sm" name="attendance_status"><?php foreach(['not_recorded','present','absent','excused'] as $st):?><option <?=$st===($p['attendance_status']?:'not_recorded')?'selected':''?>><?=$st?></option><?php endforeach;?></select><button class="btn btn-sm btn-outline-primary">Save</button></form></div><?php endforeach;if(!$found):?><p class="text-muted p-2 mb-0">No registrations.</p><?php endif;?></div></section></div><?php endforeach;?></div>
<?php $content=ob_get_clean();include __DIR__.'/../portal/layout.php';
