<?php
require_once dirname(__DIR__,2).'/core/db_connect.php';require_once dirname(__DIR__,2).'/core/sports_service.php';
header('Cache-Control: no-store, private, max-age=0');header('Pragma: no-cache');
$userId=(int)($_SESSION['user_id']??0);if($userId<=0){header('Location: '.BASE_PATH.'/login.php');exit;}
$sourceSql=sports_column_exists($pdo,'sports_applications','application_source')?'a.application_source':"CASE WHEN u.category='sports_ministry' THEN 'new_user' ELSE 'existing_user' END";
$stmt=$pdo->prepare("SELECT u.name,a.id,$sourceSql application_source,a.status,a.submitted_at,a.applicant_message FROM sports_applications a JOIN users u ON u.id=a.user_id WHERE a.user_id=? ORDER BY a.id DESC LIMIT 1");$stmt->execute([$userId]);$application=$stmt->fetch(PDO::FETCH_ASSOC);
if(!$application){header('Location: '.BASE_PATH.'/join_sports_ministry.php');exit;}
$existingUser=$application['application_source']==='existing_user';
$error='';$flash='';
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
 if(!require_csrf())$error='Your session expired. Please reload and try again.';
 elseif(($_POST['action']??'')!=='withdraw')$error='Invalid action.';
 elseif($application['status']!=='pending')$error='Only a pending application can be withdrawn.';
 else{try{$pdo->beginTransaction();$lock=$pdo->prepare('SELECT id,status,user_id FROM sports_applications WHERE id=? AND user_id=? FOR UPDATE');$lock->execute([(int)$application['id'],$userId]);$current=$lock->fetch();if(!$current||$current['status']!=='pending')throw new RuntimeException();$pdo->prepare("UPDATE sports_applications SET status='withdrawn',updated_at=NOW() WHERE id=? AND user_id=?")->execute([(int)$application['id'],$userId]);sports_audit($pdo,$userId,'application_withdrawn','sports_application',(int)$application['id'],['source'=>$application['application_source']]);$pdo->commit();header('Location: '.BASE_PATH.'/sports_application_status.php?withdrawn=1');exit;}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();$error='The application could not be withdrawn.';}}
}
if(isset($_GET['submitted']))$flash='Your Sports Ministry application was submitted.';elseif(isset($_GET['withdrawn']))$flash='Your application was withdrawn and its history preserved.';elseif(isset($_GET['updated']))$flash='Your pending application was updated.';
$explanations=['pending'=>'Your application is awaiting Sports Ministry review.','approved'=>'Your Sports Ministry membership is approved.','rejected'=>'Your application was not approved at this time. Your normal JDM access is unchanged.','withdrawn'=>'You withdrew this application. Your normal JDM access is unchanged.','suspended'=>'Your Sports Ministry participation is suspended. Your normal JDM access is unchanged.'];
ob_start();?>
<div class="row justify-content-center"><div class="col-lg-8"><div class="card shadow-sm"><div class="card-body p-4 p-md-5"><h1 class="h3">Sports application status</h1><?php if($flash):?><div class="alert alert-success"><?=escape($flash)?></div><?php endif?><?php if($error):?><div class="alert alert-danger"><?=escape($error)?></div><?php endif?><dl class="row mt-4"><dt class="col-sm-4">Applicant</dt><dd class="col-sm-8"><?=escape($application['name'])?></dd><dt class="col-sm-4">Submitted</dt><dd class="col-sm-8"><?=escape(date('j M Y',strtotime($application['submitted_at'])))?></dd><dt class="col-sm-4">Status</dt><dd class="col-sm-8"><span class="badge text-bg-secondary"><?=escape(ucfirst($application['status']))?></span></dd></dl><p><?=escape($explanations[$application['status']]??'Contact JDM Kenya for information.')?></p><?php if($application['applicant_message']):?><div class="alert alert-info"><?=nl2br(escape($application['applicant_message']))?></div><?php endif?><div class="d-flex flex-wrap gap-2"><a class="btn btn-success" href="<?=BASE_PATH?>/sports.php">Public Sports Ministry</a><a class="btn btn-outline-success" href="<?=BASE_PATH?>/sports_rules.php">Review ministry rules</a><?php if($existingUser&&$application['status']==='pending'):?><a class="btn btn-outline-primary" href="<?=BASE_PATH?>/join_sports_ministry.php">Update application</a><?php endif?><?php if($application['status']==='pending'):?><form method="post" onsubmit="return confirm('Withdraw your application?');"><?=csrf_field()?><input type="hidden" name="action" value="withdraw"><button class="btn btn-outline-danger">Withdraw application</button></form><?php endif?></div><?php if(in_array($application['status'],['rejected','withdrawn'],true)):?><p class="small text-muted mt-3 mb-0">A new application is unavailable unless JDM Kenya introduces a history-safe authorized reapplication process.</p><?php endif?></div></div></div></div>
<?php $content=ob_get_clean();
if($existingUser){$page_title='Sports Application Status - JDM Kenya';include dirname(__DIR__).'/portal/layout.php';exit;}
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Sports Application Status | JDM Kenya</title><link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.3/css/bootstrap.min.css" rel="stylesheet"></head><body class="bg-light"><nav class="navbar navbar-dark bg-success"><div class="container"><a class="navbar-brand" href="<?=BASE_PATH?>/sports.php">Sports Ministry</a><a class="btn btn-outline-light btn-sm" href="<?=BASE_PATH?>/logout.php">Logout</a></div></nav><main class="container py-5"><?=$content?></main></body></html>
